repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uvx ruff check --fix .
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: uvx ruff format .
        language: system
        pass_filenames: false
