[project]
name = "cloudtrail-watcher"
version = "0.1.4"
description = "Watch CloudTrail events and notify via Slack Webhook and SNS"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.34",
]
